name: "Build and Upload Artifacts"
on:
  workflow_dispatch:
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0-dev.2711+f995c1b08
      - uses: actions/checkout@v4
      - run: zig build -Doptimize=ReleaseFast -Dtarget=x86_64-windows
      - uses: edgarrc/action-7z@v1
        with:
          args: 7z a -tzip nese-window-x84_64.7z ./zig-out/bin/nese.exe ./zig-out/bin/SDL2.dll ./zig-out/bin/SDL2_ttf.dll
      - uses: actions/upload-artifact@v4
        with:
          name: nese-window-x84_64
          path: nese-window-x84_64.7z
      
      - run: zig build -Doptimize=ReleaseFast -Dtarget=x86_64-linux
      - uses: actions/upload-artifact@v4
        with:
          name: nese-linux-x86_64
          path: ./zig-out/bin/nese
